---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myappfe-deployment
spec:
  selector:
    matchLabels:
      app: myappfe
  replicas: 2
  template: 
    metadata:
      labels:
        app: myappfe
    spec:
      containers:
      - name: myappfe
        image: ursbrchandra/myappfrontend:1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0.5"
            memory: "200Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: testfrontend
spec:
  selector:
    app: myappfe
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
